# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMoTGHCRw7W9etYHmKFtRqqNZALpCZSz
"""

#list paremeter
def delete_head(t):
  del t[0]
letters=['a','b','c']
delete_head(letters)
print(letters)

#tuple
t1=('a',)
type(t1)

#tuple
t1=('a','b')
type(t1)

a=('entra nee badha')
type(a)

a=['entra nee badha']
type(a)

t=tuple()
print(t)

a={'Name':'sathya','Age':'20'}
print(a)

